# Generated by Django 4.1.2 on 2022-10-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_puzzle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='win_state',
            field=models.BooleanField(default=False),
        ),
    ]
